spring:
  application:
    name: kathena-backend
  profiles:
    active: dev # application-dev.yml

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

# JWT 공통 설정 (Secret Key)
jwt:
  secret: ${JWT_SECRET}

# 로깅
logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] [%X{traceId:-NO_TRACE_ID}] %-5level %logger{36} - %msg%n"